# Knative "_default" Site Configuration

# Usage notes:
# To build with these settings, see "scripts/build.sh" or "scripts/localbuild.sh"
# Also see environment specific settings in "config/production" or "config/staging".

title = "devops"
configDir = "config"
canonifyURLs = "true"
relativeURLs = "true"
enableEmoji = true
footnotereturnlinkcontents = "↩"
# Language settings
# defaultContentLanguage = "zh"
languageCode = "zh-CN"
# TODO: Investigate if this should be true when other nls exist?
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true


# Ignore files when rendering/building site (to hide from Nav tree and sitemap)
# Add files here that you "include" in other files using the 'readfile' shortcode
# Examples:
# Based on root path: {{% readfile file="docs/serving/README.md" markdown="true" %}}
# Using relative path: {{% readfile file="README.md" relatative="true" markdown="true" %}}
#
# All README.md files are ignored because they are "included" into _index.md files
# and we want the build to avoid blank nav entries and extra/duplicate sitemap entries.
# (the README.md files are kept for GitHub repo users so a landing pages appears)
ignoreFiles = [

]

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
# [blackfriday]
# plainIDAnchors = true
# hrefTargetBlank = true
# angledQuotes = false
# latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-214417-13"

